### ISSUE TITLE
UTM coordinates problem

### ISSUE THREAD

**Issue by aritzurruela** [simonbroggi/blender_spreadsheet_import#11]
Hello and thank you very much for the addon!

I am trying to import some x, y, z points with UTM coordinates but I am struggling for them to position correctly.
The scene is georeferenced (ETRS89 /UTM zone 31N) and I imported some .shp data that stays where it supposed to but when I import the .csv data even when positions in the table on the geometry nodes looks correctly, they end up in a different position in the layout. Weirdly, looking at the geo-coordinates it seems that the x and y have been multiplied by 2, not the z.

I am missing something but don’t know where to look. Can you help me?

**Comment by aritzurruela** [comment]
Hello! 

The problem I encounter is that the addon seems to assign the UTM coordinates of the points as the x/y/z of the imported points correctly in the table but then in the viewport the coordinates are different (see figure). That's what is boggling my mind. Is it possible that the addon is correcting the position in any way? 

![blender_spreadsheet](https://github.com/simonbroggi/blender_spreadsheet_import/assets/61541299/80b3ad42-464f-4e5c-9672-ec28358b7815)

**Comment by simonbroggi** [comment]
Hmm, I'm not sure wat the numbers are that your seeing in the header of the 3d viewport.
This addon doesn't modify the numbers, at least not that I'm aware of.

**Comment by aritzurruela** [comment]
It's the geo-coordinates of the data. They should be the same as the ones of the table but weirdly, aren't. 
I'll try to find a solution. Thanks for the help.
![blender_spreadsheet](https://github.com/simonbroggi/blender_spreadsheet_import/assets/61541299/b79efb77-bf56-4c60-a24a-38b42c11cde8)
