### ISSUE TITLE
Create one mesh with vertex points?

### ISSUE THREAD

**Issue by iamalessiopaoletti** [simonbroggi/blender_spreadsheet_import#12]
Hi, if I have tree colums of values, How can I have a plane with these values as vertex and the tree columns rapresent x, y and z positions?

**Comment by simonbroggi** [comment]
Construct your plane or planes according to how many rows you have by using the [Domain Size](https://docs.blender.org/manual/en/latest/modeling/geometry_nodes/attribute/domain_size.html) node.  

Use a [combine XYZ](https://docs.blender.org/manual/en/dev/modeling/geometry_nodes/utilities/vector/combine_xyz.html) node to construct a vector out of the three column values.  

Then set the positions with [set the positions](https://docs.blender.org/manual/en/dev/modeling/geometry_nodes/geometry/write/set_position.html).   

Check out the bar chart example: https://github.com/simonbroggi/blender_spreadsheet_import#bar-chart
