### ISSUE TITLE
Error message when trying to import .CSV file with capital .CSV ending (workaround: rename file to lowercase .csv)

### ISSUE THREAD

**Issue by CScottH** [simonbroggi/blender_spreadsheet_import#8]
Traceback (most recent call last):
  File "C:\Users\Scott\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\io_spreadsheet_import\__init__.py", line 284, in execute
    self.report({report_type}, report_message)
UnboundLocalError: local variable 'report_type' referenced before assignment

I get an error message when trying to import a CSV file

I am using Blender 3.4 Beta and 
V0.2.0 of this add on

System Information
OS Name	Microsoft Windows 11 Pro
Version	10.0.22621 Build 22621
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	DESKTOP-OVKK0EC
System Manufacturer	Gigabyte Technology Co., Ltd.
System Model	B460MD3H
System Type	x64-based PC
System SKU	Default string
Processor	Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz, 3600 Mhz, 10 Core(s), 20 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. F5, 11/23/2021
SMBIOS Version	3.2
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	Gigabyte Technology Co., Ltd.
BaseBoard Product	B460M D3H
BaseBoard Version	Default string
Platform Role	Desktop
Secure Boot State	On
PCR7 Configuration	Elevation Required to View
Windows Directory	C:\WINDOWS
System Directory	C:\WINDOWS\system32
Boot Device	\Device\HarddiskVolume7
Locale	United States
Hardware Abstraction Layer	Version = "10.0.22621.819"
User Name	DESKTOP-OVKK0EC\Scott
Time Zone	E. Australia Standard Time
Installed Physical Memory (RAM)	32.0 GB
Total Physical Memory	31.9 GB
Available Physical Memory	26.3 GB
Total Virtual Memory	44.9 GB
Available Virtual Memory	37.0 GB
Page File Space	13.0 GB
Page File	C:\pagefile.sys
Kernel DMA Protection	Off
Virtualization-based security	Running
Virtualization-based security Required Security Properties	
Virtualization-based security Available Security Properties	Base Virtualization Support, Secure Boot, DMA Protection, UEFI Code Readonly, SMM Security Mitigations 1.0, Mode Based Execution Control, APIC Virtualization
Virtualization-based security Services Configured	Hypervisor enforced Code Integrity
Virtualization-based security Services Running	Credential Guard, Hypervisor enforced Code Integrity
Windows Defender Application Control policy	Enforced
Windows Defender Application Control user mode policy	Off
[system-info.txt](https://github.com/simonbroggi/blender_spreadsheet_import/files/10100819/system-info.txt)

Device Encryption Support	Elevation Required to View
A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by CScottH** [comment]
OK, I solved this.
The importer is case sensitive to the extension of the file name.
It is looking for '.csv'
an extension of '.CSV' will cause this error
Note that if you export data from Excel, it appends '.CSV' as the extension.

**Comment by simonbroggi** [comment]
Thanks for pointing this out.
I'll fix this in a next release.
For now, the easy workaround for users who don't want to edit the code themselves: Rename the CSV file so it ends with lowercase `.csv`

**Comment by simonbroggi** [comment]
Should be fixed in the latest release.
