### ISSUE TITLE
Switching to a different file

### ISSUE THREAD

**Issue by CScottH** [simonbroggi/blender_spreadsheet_import#9]
Can the imported file be changed for this object:
Here is the scenario
I want to make a blender file that can import GPS data in CSV format and have it create an object that is the 3d representation of the track data. That part is pretty easy to do. But ...
If I want to use a different input file, do I have to recreate the node structure all over again?

**Comment by simonbroggi** [comment]
You don't have to recreate the Nodes.
The imported Data lives in the Geometry created by the importer.
You can use the data in your node graph with an Object Info node, and access it via the Geometry socket.
If you want to use a new dataset, simply change the Mesh data-block in the object data properties of the object you dragged into the node graph to point to the new imported geometry.

**Comment by CScottH** [comment]
Thanks for that. I will give that a try.

Regards
Scott Hendry
www.scotthendry.com
http://youtube.com/user/TheCscotthendry

On Dec 19, 2022, at 8:02 PM, Simon Broggi ***@***.***> wrote:

﻿

You don't have to recreate the Nodes.
The imported Data lives in the Geometry created by the importer.
You can use the data in your node graph with an Object Info node, and access it via the Geometry socket.
If you want to use a new dataset, simply change the Mesh data-block in the object data properties of the object you dragged into the node graph to point to the new imported geometry.

**Comment by simonbroggi** [comment]
it works
